# Generated by Django 4.2 on 2023-04-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_productattribute_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
